SELECT * FROM MEMBER;
DELETE FROM MEMBER;
INSERT ALL 
	INTO MEMBER VALUES ('이소미', 'somi', '1234', 'gmd@naver.com', '010-2362-5157', 0, sysdate)
	INTO MEMBER VALUES ('하성오', 'sang12', '1234', 'ha12@naver.com', '010-5629-8888',1, sysdate)
	INTO MEMBER VALUES ('김윤승', 'light', '1234', 'youn1004@naver.com', '010-9999-8282',1, sysdate)
	SELECT 1 FROM dual; --조건이 참이면 넣는다
	
--user check
SELECT name, userid, pwd, email, phone, admin, joindate FROM MEMBER;

SELECT PWD FROM MEMBER WHERE USERID='SOMI';

SELECT name, userid, pwd, email, phone, admin, joindate FROM MEMBER
WHERE userid = 'somi' AND pwd = '1234';


INSERT ALL 
	INTO title VALUES (1, '사장')
	INTO title VALUES (2, '부장')
	INTO title VALUES (3, '과장')
	INTO title VALUES (4, '대리')
	INTO title VALUES (5, '사원')
	SELECT 1 FROM dual;

SELECT * FROM title;
DELETE title;

DELETE department;
INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);

SELECT DEPT_NO, DEPT_NAME, FLOOR FROM DEPARTMENT;
SELECT max(dept_NO)+1 FROM department;



SELECT * FROM employee;
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(4377, '이성래', 1, NULL, 5000000, 2, 'test@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(3426, '박영권', 3, 4377, 3000000, 1, 'test1@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(3011, '이수민', 2, 4377, 4000000, 3, 'test2@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(3427, '최종철', 5, 3011, 1500000, 3, 'test3@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(1003, '조민희', 3, 4377, 3000000, 2, 'test4@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(2106, '김창섭', 4, 1003, 2500000, 2, 'test5@test.co.kr', '1234');
INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD) VALUES(1365, '김상원', 5, 3426, 1500000, 1, 'test6@test.co.kr', '1234');



CREATE OR REPLACE VIEW VW_EMPLOYEE_JOIN AS 
SELECT e.EMP_NO, e.EMP_NAME, e.TNO, e.MANAGER , e.SALARY, e.DNO, e.REGDATE, e.EMAIL , e.TEL , e.PIC_URL, 
       t.TITLE_NAME, d.DEPT_NAME, m.EMP_NAME MANAGER_NAME
  FROM EMPLOYEE e JOIN TITLE t ON e.TNO = t.TITLE_NO 
       LEFT JOIN EMPLOYEE m ON e.MANAGER = m.EMP_NO 
       JOIN DEPARTMENT d ON e.DNO = d.DEPT_NO; 
      
SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, REGDATE, 
       EMAIL, TEL, PIC_URL, TITLE_NAME, DEPT_NAME, MANAGER_NAME 
  FROM VW_EMPLOYEE_JOIN;

SELECT * FROM employee;
DELETE FROM EMPLOYEE WHERE emp_name = '김혜진';

INSERT INTO EMPLOYEE(EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD, REGDATE, TEL, PIC_URL) VALUES (1219, '김혜진', 2, 4377, 2000000, 1, 'ahjd@jdfljsk', '1234', to_date('2020-09-03','yyyy-MM-dd'), '010-565-5656', 'sdhfjhskfd')